### PR TITLE
fix for work on redis 4.0.9

### PR DESCRIPTION
**Pull request by bartigor**
Corrected to work with redis 4.0.9 Maybe someone will come in handy

### CODE REVIEW

**Comment by bjoernricks** [comment]
I don't get why this should change anything. Instead of passing the necessary arguments as keyword they are now passed as positionals.

Beyond that I even don't know how this should affect redis server directly if we only call the redis python api.

**Comment by bartigor** [comment]
With named arguments, this just doesn't work. I replaced https://redis-py.readthedocs.io/en/latest/#redis.Redis.lrem with positional ones according to the documentation and it worked.

**Comment by bjoernricks** [comment]
I don't get that
```python
def foo(a, b, c):
   print(a, b, c)

>>> foo(1, 2, 3)
(1, 2, 3)
>>> foo(1, b=2, c=3)
(1, 2, 3)
```

**Comment by bjoernricks** [comment]
Passing arguments via keywords is a standard python feature. This has nothing to do with the used redis library.

Even this works
```python
>>> foo(1, c=3, b=2)
(1, 2, 3)
```

**Comment by bartigor** [comment]
I know that python should work this way and that, but why am I getting an error
lrem() got an unexpected keyword argument 'count'
Perhaps this is due to the implementation of the python-redis library.

**Comment by bartigor** [comment]
I understand it seems there are different classes 
in StrictRedis(object)
```
  lrem(self, name, count, value)
```
in class Redis(StrictRedis):
```
def lrem(self, name, value, num=0):
```
and when you call class Redis(StrictRedis): it falls
